FROM node:14.15.0 AS builder
RUN apt-get update -qq && apt-get install -y build-essential
ENV APP_HOME /contact-list-app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD package.json .

# Add the two entries below
RUN mkdir -p node_modules/node-sass/vendor/linux-x64-51
RUN curl -L https://github.com/sass/node-sass/releases/download/v7.0.1/linux-x64-51_binding.node -o node_modules/node-sass/vendor/linux-x64-51/binding.node

RUN npm install
RUN npm rebuild node-sass
ADD . .
CMD [ "npm", "run" ,"start" ]
EXPOSE 3000
